services:
  # main application
  test-purchase-app:
    build: .
    container_name: test-purchase-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - test-purchase-db
      - pricing-svc

  # database
  test-purchase-db:
    image: mysql:8.0
    container_name: test-purchase-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_purchase_db
    ports:
      - "3307:3306"

  # rest api
  pricing-svc:
     image: pricing-svc-image:latest
     ports:
       - "8081:8081"